# Generated by Django 2.2.3 on 2020-01-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200106_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='blog.Post'),
        ),
    ]
